# Server configurations
server:
  host: "ao9moanwus0rjiex.cbetxkdyhwsb.us-east-1.rds.amazonaws.com"
  port: 3306

# Database credentials
database:
  db_name: "kd5qjovd2x28b1vz"
  user: "yxianvejg8hnzjzc"
  pass: "dkmkdku1cmwi0nnu"
